### PR TITLE
Add grouping to categories and populations

### LINKED ISSUE #276: Better method for selecting categories
It's confusing right now, but we don't know how to make it better right now.

### PR DESCRIPTION
**Pull request by radioprotector**
Closes #276.

Searching for categories now looks like the following:
search-populations

In Chrome, that box takes up the full width of the button, but in Firefox, it seems to be based on the length of the available options.

I also tried adding a "Clear" button to remove all selected categories/populations but I couldn't get it to display right.

Similarly, specifying identities gives you nicely-grouped options:
user-profile-grouped-identities

It'll list the names of selected options until you hit 4:
user-profile-selected

## Deviations from the Spec

I had to move the relationship and the backref to the individual categories/populations to get the cascades to work properly, but that's no biggie.

I also had to rename `order` to `grouporder` to avoid conflicts with SQL keywords. Flask-Admin appears to have some issues with appropriately quoting these items.

I had to heavily tweak the custom WTForms widget/field but I think the overall solution is a lot easier to understand -  it also sets us up nicely if we want to do single-selects at some point in the future.

The `buttonWidth` of any rendered multiselect is now fixed at 100%. I also customized the `buttonText` function so that the generated button text is a little more friendly than just saying "options". The singular and plural nouns used can be customized by `data-noun` and `data-nounplural` attributes on the select itself (although we currently only need to specify the pluralized version, since we're only working with multiselects).

I'm not totally happy with the Admin views for categories/populations (I'd really like to sort/filter on group), but that seems pretty difficult to do at the moment. If we upgrade to Flask-Admin 1.3.0 (I opened #286 regarding that), it might be easier to do, and it could avoid some of the workarounds that I had to do for `grouporder` (although there's no going back on that in this particular case).

### CODE REVIEW

**Comment by internetcreep** [comment]
There are a couple things I'm not totally clear on: 

I am not seeing the category grouping on your screencap, but I'm guessing those will look similar to the screencap of populations?

Identities: what happens after you select 4? Explosions?

Will the admin side of this still work similarly to now.. ie I'll have some ability to tweak things? I'm mostly thinking about the order of groups/sub-groupings.

I'm confused about what this means for the singular/plural identity stuff. Maybe it's not important?

I think this grouping is a step in the right direction, and I'm very excited. But I also think multi-level groupings will be something that will have to be investigated in the future, maybe by another human or elder god.

**Comment by radioprotector** [comment]
Yes, it looks the same for grouped categories.

When you select 4 it just abbreviates to "4 identities selected"/"4 populations selected"/"4 categories selected. (By default, it would say "4 options selected" - that's where the custom pluralization comes in to play.)

There's an "Order" field available on each of the different groups, which is configurable in Admin:
pop-group

In the user profile screenshot, "Group Z Prime" would normally go after "Group A" because of alphabetical ordering, but "Group Z Prime" has an order of `0` and "Group A" has an order of `1` so it shows up afterwards.

Within those groups, however, it does a plain alphabetical sort for the actual category/population names.

**Comment by radioprotector** [comment]
@AllieDeford: Do you want to take a look at this?

**Comment by AllieDeford** [comment]
Is the search icon in the drop down the action button to search? And does the x get rid of the module? In other places, the search icon is an action button and we place it to the right hand side of the field, so I'd like to keep the consistency

**Comment by radioprotector** [comment]
The search icon in the dropdown doesn't do anything - it gives a contextual clue as to what purpose the text box serves.

The X button is to clear the current text filter. It does not close the current module or clear what is currently selected.

You can play around with the [Bootstrap Multiselect filtering examples](https://davidstutz.github.io/bootstrap-multiselect/#configuration-options) if you want to get a better idea of how this works.

**Comment by AllieDeford** [comment]
As a user, I would have had no idea that's how it worked. I respect the need for context clues, but I don't like it looks so similar to our search button. Personally, I think we'd be fine with just the placeholder text that says search. And I suppose the clear makes sense.

**Comment by radioprotector** [comment]
I tweaked the template for the filtering UI so that the search button is omitted. The clear button for the filter now has a tooltip that indicates what it does.

**Pull request merged**
