### PR TITLE
New provider page

### LINKED ISSUE #173: Redesign Provider Page
Currently, it's hard to find the information you want, and it's not well laid out.

### PR DESCRIPTION
**Pull request by AllieDeford**
Closes #173 

There still needs to a few tweaks, mostly around reviews (which will happen once we do the reviews rework) and a few around information not yet in the database (accepting new patients, etc) 

Desktop view: 
screenshot from 2015-04-16 13 28 52

Mobile view: 
screenshot from 2015-04-16 13 30 04

### CODE REVIEW

**Comment by radioprotector** [comment]
I like it. A couple of minor nitpicks:

- Can we hide the different properties such as "Sliding Scale Fee" for now since we won't have any useful data? We can just comment out that section of the template and keep it around.
- Once we add those, I think we'll have to worry about screen readers. Bootstrap has some guidelines about how [Glyphicons can be accessible](http://getbootstrap.com/components/#glyphicons-examples). I also think it might make more sense if we render the glyphicons/textual equivalents *after* the label and use floats to ensure they show up on the left - screen readers [read in the code order, not visual order](http://accessibility.psu.edu/css/readorderhtml/).
- Would it be possible to convert the newlines in the description/hours fields [to line breaks](http://flask.pocoo.org/snippets/28/)?

**Comment by AllieDeford** [comment]
I can do the second 2, but the first one I have a comment about. I thought about that, but then I wondered if maybe we should actually leave it there because it prompts people to give a correction with that information. If it's not there, they likely might not mention it. If we don't have the backend support that, I agree. But if the back end supports it, I think we should leave it as a prompt

**Comment by radioprotector** [comment]
Right now the backend doesn't, and I think the insurance options can get a lot more varied. I think we'd have to figure that out adequately before we could start storing it in the backend. That also has implications for the radrecord format.

**Comment by AllieDeford** [comment]
Alright, I've hidden it for now. But I opened #204 to deal with it. I think I'm ready for you to look at it again

**Comment by radioprotector** [comment]
One last nitpick - can we also apply the nl2br filter to the description field?

**Comment by radioprotector** [comment]
@AllieDeford - when you get the time can you add that one extra nitpick? After that, I think this can be closed out.

**Comment by AllieDeford** [comment]
okay, so I made that change, and also updated the front page with Riley's new message. I don't love the photo of him, because it's not very high quality. But other than that, it's alright.

**Comment by rileydjohnson** [comment]
I will ask Rachel to take a new one. :)

**Comment by radioprotector** [comment]
This otherwise looks pretty good. I can merge it unless we're still waiting for the updated picture.

One side note to watch out for is when stuff is getting pasted in through Word - it tends to include [smart quotes](https://en.wikipedia.org/wiki/Quotation_mark#Curved_quotes_and_Unicode) for items, which don't always render right on certain devices. Whenever I see those, I try to replace them with the standard straight quotes. I noticed that the new blurb uses curved quotes for the apostrophes ("`’`").

**Comment by AllieDeford** [comment]
I read through it and thought there weren't any, but I missed that one. The apostrophes always slip past me. Let's merge it and we'll just add the picture later

**Pull request merged**
