### PR TITLE
Frontpage fixes

### LINKED ISSUE #208: Fix some issues with the new front page
The extra margin on the Donate Here button throws off the alignment on the navbar:

donate-now-button

I'll decrease the vertical padding on the actual "Donate Now" anchor to compensate for the extra padding.

I also noticed the "About" section link actually goes to "How to Use", which should be simple enough to fix.

Finally, in the extra-small view, the navbar looks kind of weird and Riley's picture gets blown up a bunch:

xs-view

I'll look into decreasing the margin on that navbar and I think we're probably better off just hiding Riley's image in that view (sorry, Riley!).

### PR DESCRIPTION
**Pull request by radioprotector**
Closes #208.

I also noticed that the headshot had a `width: 100%` style on it, which would blow up the image way beyond its original dimensions, which is particularly apparent in extra-large views:

extra-large-headshot

I replaced it with an `img-responsive` class which ensures that it won't spill over in smaller views, but won't get expanded beyond its original proportions. I also hid this headshot in the extra-small mobile view.

The nav bar regularly now looks like the following in smaller views and above:
small-view

The extra-small view now no longer right-floats the "Donate Button":

xs-view

The best looking (but also the most fragile) solution would be to detect the width at when the navbar would wrap and only remove the float at that point. Given how much we're still working on the UI, I'm really hesitant to go that far at this point. However, the adjustment I made really comes in handy when our navbar gets small enough to span multiple lines:

xs-wrapping-view

This still works even when we have more items breaking onto the second line:

xs-more-wrapping-view

I'm not super enthusiastic about retaining the right float because otherwise it can result in weirdness like the following (when the second row doesn't take up the full allocated width):

xs-weird-view

### CODE REVIEW

**Comment by lovecultivated** [comment]
I will get my act together and take a high res photo of him sometime this
week. That should be at least somewhat helpful.

Start getting pretty, Riley

**Comment by radioprotector** [comment]
Okay. Let's hold off on merging this in and I can include the new picture once it's available, although that will be a little more difficult for me to do when I'm on the road (next Monday to Sunday).

**Comment by lovecultivated** [comment]
I will try to do it this weekend and get it to you by Sat night. I have to
see him in the daylight and with charged camera battery, so I suspect Sat
is the earliest.

**Comment by radioprotector** [comment]
Okay, I updated this with the new headshot and added one or two other minor tweaks.

**Pull request merged**
