### PR TITLE
Web updates

### LINKED ISSUE #169: Update information pages (About Us, Projects, Volunteering, etc.) on main site
The information that's now available on [our placeholder site](http://radremedy.org/) needs to also be in our site.

### PR DESCRIPTION
**Pull request by AllieDeford**
Closes #169

### CODE REVIEW

**Comment by AllieDeford** [comment]
@radioprotector If you have a chance to merge this before the board meeting tomorrow, that would be nice. Otherwise, it'll just be done when you get a chance!

**Comment by radioprotector** [comment]
Can you fix the title on the About Us page that says "Oraganizational Team"? Other than that, this looks good.

**Comment by radioprotector** [comment]
Oh, also the diff looks like the Coming Soon section for projects is missing its closing `dl` tag.

**Comment by AllieDeford** [comment]
Done

**Pull request merged**
