### PR TITLE
Add user-facing submission of providers

### LINKED ISSUE #185: Add way for logged-in users to suggest new resources
Continuing [the discussion from #182](https://github.com/radremedy/radremedy/pull/182#issuecomment-77666188), we could have a suggestion form for logged in users.

This would be linked to from the search page when no results are available, and if we update the "Recently Added" portion on the front page to filter based on location, we could add it there as well.

### PR DESCRIPTION
**Pull request by radioprotector**
Closes #185.

## Functional Overview

Here's what the full submission form looks like for a user:
submitted-resource-user

And here's what the message looks like after it's been submitted:
user-submitted-message

From an Admin perspective, you get the following form. Duplicate detection is on the basis of name or NPI:
submitted-resource-admin

I also managed to carry over some of the new form grouping to the main resource editing page:
resource-edit-admin

Because the concept of `visible` is tied into the approval process, it can't be edited on resources that have yet to be approved (either on the standard editing page or the "Toggle Visible" action).

Other nice enhancements I managed to get through:

- Multiline text fields such as a provider's description and hours now generate URLs. This is *not* enabled for the text of a review.
- Resource and user links are generated where appropriate.
- Line breaks are respected on multiline text fields in Admin detail and list views.
- I worked around a weird CSV export issue that was only caused when an 'ID' column was the first column in the exported file.

### General Changes

We updated the `nl2br` filter to support generation of URLs in this content. As part of this, we upgraded to Jinja 2.8.0 because it added an additional 'target' parameter that we needed for its `urlize` function.

A new `remedy_utils.get_field_args` method was added to the default execution context. It accepts a WTForms field instance and a variable number of arguments (used to add/override field attributes as needed) and returns a dictionary of attributes that should be used when rendering out the corresponding WTForms instance.

I also separated out the basic handling of `nl2br` and `phoneintl` processing into `remedy_utils`, which makes it easier to call in Admin stuff (more on that later). I also moved `flash_errors` from `remedyblueprint` to `remedy_utils` to help cut down on the size of stuff in `remedyblueprint`.

### User-Facing Changes

I added a new `form_group` macro to help simplify the process of rendering WTForms fields. This was applied to the following templates:

- `add-provider.html`
- `create-account.html`
- `review-block.html`
- `settings.html`

If we get all of the WTForms-based templates using this, we can easily close out #270.

I had to extract out just the script component needed for adding reviews to a new `review-block-scripts.html` template.

I also added some macros to help consolidate the inclusion of the Bootstrap-Multiselect script, initialization of such fields, and popover initialization.

I removed the `provider` field from the standard `ReviewForm` form because it was redundant with what we already had on the endpoint and wasn't really being used at all. I also fixed some weird CSS issues with Chrome for the rating stars.

### Admin-Facing Changes

I ended up creating a `StaticHtmlField` that is used for displaying - you guessed it - static HTML. This is used to generate appropriate links to items where appropriate in the resource views.

I consolidated the generation of column labels, descriptions, and formatters in `admin_helpers`. This allows for better cross-linking and formatting of multiline text fields in all Admin list/detail pages. I applied such formatting where appropriate, but had to disable it for the CSV exports.

I also updated the main Admin view to filter out hidden reviews/resources and the like.

I had to make the `submitted_resource_edit.html` template inherit from the base `master.html` instead of `edit.html`, which meant I had to copy/paste a bit more boilerplate.

From a main resource view, I had to override edit_form and the visibility toggling action to prevent changing the visible status of unapproved resources. I also updated the `form_rules` to parallel what's now available in the main resource view.

### CODE REVIEW

**Comment by internetcreep** [comment]
So many great things here Cate! I have a few questions and notes, mostly user interface stuff.

Can we get an extra line break at the beginning after "Provider Information" (and maybe center that text).

The description text under the titles (Provider Name, etc) is bigger than the title text, which makes it look too prominent. So maybe just swap those font sizes.

Will the address field be linked to geocoding or will we need to do that on our end?

ADA/Handicap Accessible --> ADA/Wheelchair Accessible

On the admin side, it looks like hospital affiliation and the 4 flags are listed under contact information?

Will the user get notified when their submission is approved/rejected? Or will we need to do that manually?

What does this mean: "Multiline text fields such as a provider's description and hours now generate URLs"? If someone inputs a URL in those fields, it will link it? Or that it links to their website (if listed)?

What does this mean: "Resource and user links are generated where appropriate." Are we linking to user profiles?

Also, I didn't see anything here about what the flow looks like for folks not logged in. I know you said we could add specific text/messages based on that, so I didn't know if you needed copy/wording from me.

One bigger thing, that I feel like we talked about it in a meeting, but I don't know if it got written down anywhere. Before the user gets to this page, could there be a page with two buttons: user submissions vs. provider input? I think that will help filter out misuse of this form that is similar to what's happening on the google doc. Would this totally fuck up what you've done so far?

**Comment by radioprotector** [comment]
I'll include some sample screenshots for the multiline text fields, the user/resource links, and what happens for users that aren't logged in. I basically just copied your suggestion from earlier verbatim.

The address geocoding will need to happen on our end.

There's no automated notification that takes place when submissions are approved/rejected.

I'll make the changes to the title/description text and the ADA field label. The flags/hospital affiliation stuff are actually in a separate section, but I didn't have a good idea how to title it so there's just a blank space where a title would normally be.

Changing the routing for the form would kind of be throwaway work. Eventually we'll have separate pages/forms for organizations/providers and so clicking that link would route someone to the appropriate form based on how their user record is flagged.

**Comment by radioprotector** [comment]
Okay, so here's some clarification.

Here's what the login message looks like:
sign-up-message

Here's what the provider multiline fields look like - note that the review fields do *not* get autolinked:
provider-field-multiline

review-text-multiline

In the original submission screenshot you can see that the WPATH and ICATH links are also autolinked - this is also supported for help text.

Finally, here's what I mean by Admin links:
admin-links

**Comment by internetcreep** [comment]
Thanks for the extra screenshots. It all looks good to me!

**Comment by internetcreep** [comment]
If the "Provider Information" is the only heading that is in the user-facing form, it's a bit redundant and we don't actually need it. So you wouldn't have to make the formatting changes on that line.

**Comment by radioprotector** [comment]
The Review section uses a heading waaaaay down the page.

**Comment by internetcreep** [comment]
The "Your Review" header is definitely necessary. But for the others (basic, contact, practice, other), I vote either all of them or none of them. Up to you. Using the headings might break it up and make it seem less overwhelming, but it could also do the opposite.

**Comment by radioprotector** [comment]
## Further Functional Changes

I made the flashed messages display a little more contextually - success has a nice green format, errors have red formatting, warnings have yellow formatting, and everything else defaults to blue.

I updated the styles for the labels/help text to be a little more consistent - the labels are now the same size as an `h4` and the help text is now slightly smaller than the labels.

I added the "Practice Information" heading and added some more headings/horizontal rules to make things break out more nicely. I also fixed up that "ADA/Wheelchair Accessible" label.

The editing page for reviewing submissions now includes a `mailto:` link to directly email the user concerning the submission.

## Further Tech Changes

I added a new `remedy_utils.get_grouped_flashed_messages` method to help group flashed items in a semantically-appropriate way. This is registered as a custom function in both the standard remedy and authentication blueprints and is used by a new `render_flashed_messages` macro, which is in turn used in `base.html` for all flashed messages. I tried to update all `flash` calls to use an appropriate category, when available.

There's a new `admin_helpers.get_email_link` method that will generate a `mailto:` link (with an optional subject) for the provided user. The "Submitted User" field when editing a submission now uses this to include an email address alongside the user link.

To get the label stuff consistent, I ended up having to standardize a bunch of templates (mostly user auth-related) to use the new `form_group` macro. In the process I determined that I needed to override the description used for the login form. However, these changes mean that this PR now also closes #270.

**Comment by radioprotector** [comment]
@internetcreep: Are you cool with the revisions?

**Comment by internetcreep** [comment]
Yes! :party:

**Pull request merged**
