### PR TITLE
Add better styling to review entry/display

### PR DESCRIPTION
**Pull request by radioprotector**
The entry form uses the same radio buttons as before, but with [some special CSS](http://jameschambers.com/2014/09/using-font-awesome-in-an-accessible-bindable-star-rating-control/) to achieve the stars/N/A effect.

This is what you see initially for a review (after taking these screenshots though, I did change the styling on the question marks to use the rad-purple color):
initial-view

When hovering over a new rating to select:
hover-view

After you've selected a rating and you're hovering over a new higher rating, the proposed rating is in pink and the existing rating is in blue:
higher-rating-view

If you're hovering over a new lower rating, you see your existing rating similarly highlighted in purple and your lower rating in blue:
lower-rating-view

Finally, I styled the 1-5 ratings on the page, going from rad-blue (the lowest rating) to rad-purple (the middle) to rad-pink (the highest rating). N/A items are omitted:
rating-colors

### CODE REVIEW

**Comment by AllieDeford** [comment]
Without your explanation, the colors would have been very confusing to me, so I imagine they would be to a potential user as well. My suggestion to to always use 1 color for highlighting and 1 color for after you click. For example, while you are deciding, the hover is pink. Once you click, they turn blue. If you hover again, the stars turn pink while hovering, and the only blue rating comes back after you mouse out or a new blue rating occurs if you select a new number. Does that makes sense?

**Comment by AllieDeford** [comment]
Also, we should take the IP out of the comments. They still need styling work, but we can leave them for now.

**Comment by radioprotector** [comment]
If you look at the template, the IPs are only visible if you're logged in as an administrator. I wanted to make it as easy as possible to identify possible sockpuppeting of reviews.

The template is a little harder to explain in words and with the screenshots because you don't see where my mouse cursor is. It might be one of those things where it's actually a little clearer to try out in person - I think I might be failing to describe it adequately.

I am not enthusiastic about using the light blue for the stars of a selected rating. It doesn't seem to contrast with the background particularly well.

**Comment by rileydjohnson** [comment]
I just wanted to thank you both for your attentiveness to these issues. The
identification of sockpuppeting is critical in my opinion to the success of
the database.

Thanks y'all!
R.

**Comment by AllieDeford** [comment]
Feel free to move the colors around as you see fit. It's just the general interaction pattern that it important to me. When I was working on it, I did the pink for all the hover actions and the purple for selected

**Comment by radioprotector** [comment]
The one thing is that it might look confusing if we're still going to show the existing rating relative to the new rating we're hovering over, particularly if we're hovering over a smaller rating, because it wouldn't appear to be actually changing - imagine all of the following stars being pink or something:
lower-rating-view

**Comment by rileydjohnson** [comment]
In the example provided, I'd prefer the rated stars being darker than the
other ones to avert the confusion. For an example of this, see Netflix as
you're rating.

Thanks!
R.

**Comment by AllieDeford** [comment]
If you're hovering over a lower rating (for example, if you had selected 4 and now you were hovering over two) you would only see the two blue stars

**Comment by radioprotector** [comment]
I got the styling working with just pink and grey when you're hovering, so I think this is good to go.

**Pull request merged**
