### PR TITLE
Rework list of new providers on index page

### LINKED ISSUE #177: Arrows for new provider cards aren't stable in layout
Sometimes they look okay, sometimes they don't. Depends on screen size and zoom-ed in factor. 

screenshot

For example, like this

### PR DESCRIPTION
**Pull request by radioprotector**
Closes #177.

I also standardized these to say "Provider" instead of "Resource", as it seems like we're using "Provider" most other places in the user-facing views.

This is forked from #180 and so that PR should be accepted before this one is.

I changed these to use cards and have a more/less toggle:
recently-added-showmore

recently-added-showfewer

### CODE REVIEW

**Comment by AllieDeford** [comment]
This looks good, but I had a later thought- should we maybe add a location in smaller font under the resource name? I feel like the name alone isn't actually that interesting to people; they really only care if that resource is accessible to them. Just a City, State combo would be good I think. 

Thoughts?

**Comment by rileydjohnson** [comment]
I like this addition.
Do you feel we need specialty as well or no?

**Comment by AllieDeford** [comment]
I think that might make it too cluttered for now. I think once we get user-facing categories figured out, it might be interesting to explore adding that, but for now we don't know what that data looks like

**Comment by rileydjohnson** [comment]
Cool. That sounds like a good plan. Thanks for all you do, y'all. Such
great work!

**Comment by radioprotector** [comment]
Huh, I thought I replied by email, but maybe it got lost?

Anyway, one of the challenges is the fact that we don't store just city/state (or even zip) as a separate field - we use a unified address field when we do geocoding, so we'd have to figure some way to parse that out if we wanted to show a general locality.

Alternatively, when someone's logged in and has a default location specified on their profile, we could tailor the "Recently Added" list to only stuff in that area.

Anyway, what should be the next steps for this?

**Comment by rileydjohnson** [comment]
Could we do location on for those logged in and without for those not
logged in?

**Comment by radioprotector** [comment]
We could, but then we'd have to deal with when there's nothing in the user's area. That, of course, would be a good opportunity to have something like "Know of something we don't have? Suggest one!" with a suggestion form.

We could also make that available on the search page for logged-in users.

**Pull request merged**
