### PR TITLE
New Nav

### LINKED ISSUE #178: Changing Font
There has been some discussion about changing the main font from Open Sans Condensed to Open Sans. We should figure out if that looks good and make necessary size changes on text if so

### PR DESCRIPTION
**Pull request by AllieDeford**
This has the nav changes, and a few other small changes. It cleans up everything from #179 that I think is small enough that it doesn't need it's own issue to handle (such as implementing the new provider page and text changes that go to Riley). 

I'm done with it for now, but I expect to still receive thoughts from Dan.

Oh, also closes #178

### CODE REVIEW

**Comment by radioprotector** [comment]
Here's my initial observations:

- We switched the font over to Open Sans (in terms of the Google Font loading) but didn't update remedy.css to mention it.
- The links I see when I'm logged in are odd (maybe we should consistently either `btn-link` or `btn-default`?):

user-navbar-links

- In that vein, we might also want to consider expanding the space allocated to these links (maybe a `col-sm-3` would work in conjunction with dropping the search to a `col-sm-6`) and also shortening "Admin Panel" to just say "Admin" for space concerns.
- Could we add a `span.sr-only` to the h1 to include "RAD" so screen readers don't see just "Remedy"?
- Maybe we could use a [jumbotron](http://getbootstrap.com/components/#jumbotron) for the front page and not have to use our own display-box styling?
- Could we use the standard [Bootstrap float classes](http://getbootstrap.com/css/#helper-classes-floats) instead of rolling our own `float-right` class for stuff in the nav bar?
- Could we change the social media links at the bottom to use the [Bootstrap img-circle shape](http://getbootstrap.com/css/#images-shapes)? We could also do a selector like `div.icon-list img` to take care of any specific styles that we need instead of having to add a `sm-icon` class to every image.
- The h3 small style that was removed is used on the donations page to make things like "Tax deductible" contrast better with the page background, so I think we need to add that back in:

h3-small

- I think we need CSS to highlight actual links - the "volunteer form" link isn't visible in the following example:

link-color

- We show the "Contact" h4 on the provider page even if we don't have any contact information, so it ends up looking really odd. I think we could check for `provider.phone or provider.fax or provider.email or provider.url` before rendering out that header.
- Right now, if I type information into the header search bar, the resulting search page doesn't include them at all. That's because the search bar in the top needs to use the field names `search`, `addr`, `lat`, `long`, and `dist` to actually be recognized by the searching page (all of which are listed in `remedyblueprint.resource_search()`). To avoid having to use a different name/ID for the labels to work, I think we can place the inputs within each label (in which case the `for` attribute is not needed).
- Also in that vein, the location field for the search header needs to be wired up to the Google Maps autocomplete or it won't end up doing anything. We have a macro for doing this (`macros.gmaps_script`) but it needs to be updated to prevent double-inclusion of the Google Maps JavaScript when we would have multiple instances of this autocomplete on a page (such as in the user settings page or the full search page). If it's going to be everywhere, we could just move the Google Maps script include to `base.html` and remove the inclusion from the macro. 
- In the top search bar, we need a a hidden `dist` field that bakes in the distance (maybe 25 or 50?). The location based searching only works when you have `addr`, `dist`, `lat`, and `long` all provided.
- If we're going to support locations, we shouldn't include the `autofill` hidden field.

**Comment by AllieDeford** [comment]
Okay, I tackled a bunch of these. I tried to make a commit for each point, but I forgot once or twice. I think I've addressed everything except getting the 3rd and 4th points from the end, which have to do with getting the Google maps script to work. Since you've been heading that up, would you be able to do that part? I could probably figure it out, but it will take me much longer than it will take you.

**Comment by radioprotector** [comment]
Do we need to use a new `no-decoration` CSS class for anchor tags or can we get away with using `div.header.row a` and `div.row.bar a` selectors? That should be sufficiently specific to override the global styling for the `a` element.

I can take care of the Google Maps stuff but if we want to do that I'd prefer to handle it as a separate PR.

**Comment by radioprotector** [comment]
I also see some odd wrapping now:
search-field-wrapping

I can see if I can fix that too as part of the other search changes, if you prefer.

In addition, should we show this quick search if someone's already on the main search page?

**Comment by AllieDeford** [comment]
I think the odd wrapping is due to changing from col-sm-6 from col-sm-7 to accommodate the buttons more appropriately. And for consistency, I think we should have the quick search on the main search page, though I don't expect anyone to use it

**Comment by AllieDeford** [comment]
Alright, I think I'm done!

**Comment by AllieDeford** [comment]
Opened #192 for fixing the quick search

**Pull request merged**
